project_name: sample-data-solution
version: 1.1.0
cloud_platform: azure
workstream: Sample workstream
description: This is a sample Data Solution project configuration file.

usage_stats:
  - telemetry: True

resources:
  iac:
    description: Responsible for managing infrastructure as code.
    custom: true
    path: .devops\iac
    format: arm # terraform, pulumi, arm, bicep etc.
    config-file: iac_config.yaml
  cicd:
    description: Responsible for managing CI/CD pipelines.
    custom: false
    path: .devops\cicd
    engine: azuredevops # azuredevops, github, gitlab etc.
  data_orchestrator:
    enabled: true
    custom: false
    description: Responsible for orchestrating the entire data pipeline.
    jobs-path: orchestration\jobs
  ingestion:
    enabled: true
    custom: false
    description: Responsible for collecting raw data from various sources.
    mode: batch # batch, streaming, hybrid
    path: ingestion
    pre-process: false
    engine: adf # adf, databricks, airflow, mixed etc.
    dataset-path: datasets
  data_quality:
    description: Ensures data quality and integrity throughout the solution.
    zones: 
    - bronze
    - silver
    - gold
    format: dbt
  transformation:
    enabled: false
    description: Handles data processing and transformation.
    mode: batch # batch, streaming, hybrid
    path: transformation
    engine: dbt # dbt, databricks etc.
    config-file: dbt_project.yaml
  integration:
    description: Manages data integration and merging from multiple sources.
    format: mixed # dbt, databricks etc.
  sharing:
    enabled: false
    description: Facilitates sharing of processed data with stakeholders.
    engine: snowflake # snowflake, databricks etc.
  consumption:
    description: Deals with data consumption by end-users or applications.
    format: PowerBI # powerbi, tableau, databricks, mixed etc.

targets:
  dev:
    description: Development environment.
