default_context:
    project_name: "Data Solution"
    created_by: "Kimani"
    version: "1.0.2"
    cloud_platform: "azure"
    workstream: "DataEngineering"
    description: "This is a sample Data Solution project configuration file."
    devops: "y"
    ingestion: "y"
    transformation: "y"
    target_platform: "databricks"
    target_schema: "dev"
    data_quality: "y"
    sharing: "y"
    usage_stats: true
    sample_data: "y"
    placeholder_files: false
    debug_run: false