project_name: {{ cookiecutter.project_name }}
version: {{ cookiecutter.version}}
cloud_platform: {{ cookiecutter.cloud_platform }}
workstream: {{ cookiecutter.workstream }}
description: {{ cookiecutter.description }}

usage_stats:
  - telemetry: {{ cookiecutter.usage_stats }}

resources:
  {%- if cookiecutter.iac == "y" %}
  iac:
    enabled: true
    description: Responsible for managing infrastructure as code.
    custom: 
      enabled: true
      path: core
    format: arm # terraform, pulumi, arm, bicep etc.
  {%- endif %}
  {%- if cookiecutter.cicd == "y" %}
  cicd:
    enabled: true
    description: Responsible for managing CI/CD pipelines.
    custom: 
      enabled: true
      path: core
    engine: azuredevops # azuredevops, github, gitlab etc.
  {%- endif %}
  {%- if cookiecutter.orchestration == "y" %}
  orchestration:
    enabled: false
    custom:
      enabled: true
      path: orchestration
    description: Responsible for orchestrating the entire data pipeline.
    mode: mixed # batch, event, hybrid
    engine: hybrid_azure # adf, databricks, airflow, hybrid_aws, hybrid_azure etc.
  {%- endif %}
  {%- if cookiecutter.ingestion == "y" %}
  ingestion:
    enabled: true
    custom: 
      enabled: true
      path: ingestion
    description: Responsible for collecting raw data from various sources.
    mode: batch # batch, streaming, hybrid
    config-format: json
    pre-process: false
    engine: adf # adf, databricks, airflow, mixed etc.
  {%- endif %}
  {%- if cookiecutter.data_quality == "y" %}
  data_quality:
    description: Ensures data quality and integrity throughout the solution.
    zones: 
    - bronze
    - silver
    - gold
    format: dbt
  {%- endif %}
  {%- if cookiecutter.transformation == "y" %}
  transformation:
    enabled: false
    custom: 
      enabled: true
      path: dbt
    description: Handles data processing and transformation.
    mode: batch # batch, streaming, hybrid
    engine: dbt # dbt, databricks etc.
  {%- endif %}
  {%- if cookiecutter.integration == "y" %}
  integration:
    description: Manages data integration and merging from multiple sources.
    format: mixed # dbt, databricks etc. 
  {%- endif %}
  {%- if cookiecutter.sharing == "y" %}
  sharing:
    enabled: false
    description: Facilitates sharing of processed data with stakeholders.
    engine: snowflake # snowflake, databricks etc.
  {%- endif %}
  consumption:
    description: Deals with data consumption by end-users or applications.
    format: PowerBI # powerbi, tableau, databricks, mixed etc.
targets:
    description: Development environment.
