default_context:
    project_name: "Data Solution"
    created_by: "Kimani"
    version: "1.1.0"
    cloud_platform: "azure"
    workstream: "DataEngineering"
    description: "This is a sample Data Solution project configuration file."
    cicd: "y"
    iac: "y"
    ingestion: "y"
    transformation: "y"
    target_platform: "databricks"
    target_schema: "dev"
    data_quality: "y"
    orchestration: "y"
    integration: "y"
    sharing: "y"
    sample_data: "y"
    placeholder_files: false
    debug_run: false