default_context:
    project_name: "Data Project 1"
    created_by: "Kimani Mbugua"
    version: "1.0.0"
    environment: "azure"
    target_platform: "databricks"
    devops: "y"
    data_ingestion: "y"
    data_transformation: "y"
    data_quality: "y"
    data_observability: "y"
    sample_data: "y"
    target_schema: "dev"